# Generated by Django 2.2.5 on 2019-09-27 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementTraceAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_method', models.CharField(blank=True, max_length=50, null=True)),
                ('iron_ppm', models.IntegerField(blank=True, null=True)),
                ('arsenic_ppm', models.IntegerField(blank=True, null=True)),
                ('copper_ppm', models.IntegerField(blank=True, null=True)),
                ('silver_ppm', models.IntegerField(blank=True, null=True)),
                ('gold_ppm', models.IntegerField(blank=True, null=True)),
                ('chromium_ppm', models.IntegerField(blank=True, null=True)),
                ('zinc_ppm', models.IntegerField(blank=True, null=True)),
                ('cobalt_ppm', models.IntegerField(blank=True, null=True)),
                ('nickel_ppm', models.IntegerField(blank=True, null=True)),
                ('antimony_ppm', models.IntegerField(blank=True, null=True)),
                ('sulfur_ppm', models.IntegerField(blank=True, null=True)),
                ('bismuth', models.IntegerField(blank=True, null=True)),
                ('cadmium', models.IntegerField(blank=True, null=True)),
                ('indium', models.IntegerField(blank=True, null=True)),
                ('manganese', models.IntegerField(blank=True, null=True)),
                ('lead', models.IntegerField(blank=True, null=True)),
                ('selenium', models.IntegerField(blank=True, null=True)),
                ('tellurium', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='metal',
            old_name='analysis_method',
            new_name='time_period',
        ),
        migrations.AddField(
            model_name='metal',
            name='element_trace_assay_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metal.ElementTraceAssay'),
        ),
    ]
