# Generated by Django 2.2.5 on 2019-11-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0003_auto_20190930_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsotopeTraceAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_method', models.CharField(blank=True, max_length=50, null=True)),
                ('delta_copper_65', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_208_to_206', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_207_to_206', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_206_to_204', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='metal',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='metal',
            name='isotope_trace_assay_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metal.IsotopeTraceAssay'),
        ),
    ]
