# Generated by Django 3.0 on 2019-12-09 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0004_auto_20191101_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('museum_number', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('element_trace_assay_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metal.ElementTraceAssay')),
                ('isotope_trace_assay_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metal.IsotopeTraceAssay')),
            ],
        ),
    ]
