# Generated by Django 3.0 on 2019-12-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0005_ore'),
    ]

    operations = [
        migrations.AddField(
            model_name='ore',
            name='mineral',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
