# Generated by Django 3.0 on 2020-03-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0006_ore_mineral'),
    ]

    operations = [
        migrations.AddField(
            model_name='metal',
            name='mineral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metal',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metal',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metal',
            name='museum_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metal',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metal',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metal',
            name='time_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
