# Generated by Django 3.0 on 2020-03-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0007_auto_20200328_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementtraceassay',
            name='iridium_percent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='elementtraceassay',
            name='osmium_percent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='elementtraceassay',
            name='palladium_105_percent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='elementtraceassay',
            name='palladium_106_percent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='elementtraceassay',
            name='palladium_108_percent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='elementtraceassay',
            name='ruthenium_101_percent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='elementtraceassay',
            name='ruthenium_99_percent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
