# Generated by Django 3.0 on 2020-03-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0008_auto_20200328_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementtraceassay',
            name='rhenium_percent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='elementtraceassay',
            name='rhenium_ppm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
