# Generated by Django 3.0 on 2020-03-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0009_auto_20200328_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementtraceassay',
            old_name='iridium_percent',
            new_name='iridium_ppm',
        ),
        migrations.RenameField(
            model_name='elementtraceassay',
            old_name='osmium_percent',
            new_name='osmium_ppm',
        ),
        migrations.RenameField(
            model_name='elementtraceassay',
            old_name='palladium_105_percent',
            new_name='palladium_105_ppm',
        ),
        migrations.RenameField(
            model_name='elementtraceassay',
            old_name='palladium_106_percent',
            new_name='palladium_106_ppm',
        ),
        migrations.RenameField(
            model_name='elementtraceassay',
            old_name='palladium_108_percent',
            new_name='palladium_108_ppm',
        ),
        migrations.RenameField(
            model_name='elementtraceassay',
            old_name='rhenium_percent',
            new_name='ruthenium_101_ppm',
        ),
        migrations.RenameField(
            model_name='elementtraceassay',
            old_name='ruthenium_101_percent',
            new_name='ruthenium_99_ppm',
        ),
        migrations.RemoveField(
            model_name='elementtraceassay',
            name='ruthenium_99_percent',
        ),
    ]
